#	$NecBSD: Makefile,v 1.6 1999/08/05 08:53:20 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

PROG = apmconfig
SRCS = apmconfig.c

#BINOWN=	root
#BINGRP=	operator
#BINMODE=4550

MKMAN = no

.include <bsd.prog.mk>
