#	$NecBSD: Makefile,v 1.8 1999/08/05 08:53:40 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
#

PROG=	apmd
MKMAN=	no
SRCS=	apmd.c apmprint.c
CPPFLAGS+=	-I../apmctrl

.PATH:	../apmctrl

.include <bsd.prog.mk>
