#	$NecBSD: Makefile,v 1.10 1998/03/14 07:01:46 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	rdstart
NOMAN=	noman
BINDIR?=	/sbin/rdstart
LDSTATIC=	-static

.include <bsd.prog.mk>
