#	$NecBSD: Makefile,v 1.14 1999/08/02 17:14:24 honda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

SUBDIR=	cdplay comctrl idectrl snd sndctrl playmidi

.include <bsd.subdir.mk>
