#	$NecBSD: Makefile,v 1.7 1999/08/05 08:53:35 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	vpdconfig
SRCS=	vpdconfig.c
MKMAN=	no

.include <bsd.prog.mk>
