#	$NecBSD: Makefile,v 1.9 1999/08/05 08:53:46 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	dumpcis
MKMAN=	no
CPPFLAGS+=	-I${.CURDIR}/../../../..

.include <bsd.prog.mk>
