# $NecBSD: Makefile,v 1.2 1998/12/21 05:45:41 kmatsuda Exp $
# $NetBSD: Makefile,v 1.3.2.1 1998/11/04 17:38:37 cgd Exp $

INCSDIR= /usr/include/machine

#INCS=   pcvt_ioctl.h
#INCS=   ${.CURDIR}/../pcvt/pcvt_ioctl.h

SUBDIR+= Util

.include <bsd.inc.mk>
.include <bsd.subdir.mk>
