#	$NecBSD: Makefile,v 1.9 1999/08/05 08:53:56 kmatsuda Exp $
#	$NetBSD: Makefile,v 1.4 1995/12/30 18:14:01 thorpej Exp $
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
#

PROG=	vnconfig
MKMAN=	vnconfig.8

.include <bsd.prog.mk>
