#	$NecBSD: Makefile,v 1.7 1999/08/05 08:53:52 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

PROG=	pnpinfo
MKMAN=	pnpinfo.8
LDADD=	-li386

.include <bsd.prog.mk>
