#	$NecBSD: Makefile,v 1.8 1999/08/05 08:53:00 kmatsuda Exp $
#	$NetBSD$

# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.

PROG=	loadmaru
MKMAN=	no
BINDIR?=	/usr/local/bin
LDSTATIC=	-static

.include <bsd.prog.mk>
