#	$NecBSD: Makefile,v 1.3 1999/08/05 08:53:31 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1999 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

PROG=	ttycon
SRCS=	ttycon.c
MKMAN=	no

.include <bsd.prog.mk>
