#	$NecBSD: Makefile,v 1.7 1999/08/05 08:53:33 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	vm86biosd
SRCS=	vm86biosd.c
MKMAN=	no
LDADD+=	-li386

.include <bsd.prog.mk>
