#!/bin/sh
#
#	$NecBSD: etherstart,v 1.5 1998/03/14 07:11:16 kmatsuda Exp $
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

/sbin/ifconfig $1 inet `/bin/hostname`
