#!/bin/sh
#
#	$NecBSD: modemstart,v 1.5 1998/03/14 07:11:21 kmatsuda Exp $
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

/sbin/ttyflags -a
