#	$NecBSD: Makefile.inc,v 1.6 1998/03/14 07:11:35 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

#WARNS?=	1
BINDIR?=	/usr/sbin
