#	$NecBSD: Makefile,v 1.9 1999/07/24 05:55:14 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

# XXX: kill vnconfig
#SUBDIR= apmctrl apmd cardinfo devid dumpcis fdc iopinfo ippinfo \
#	slotctrl vnconfig
SUBDIR= apmctrl apmd cardinfo devid dumpcis fdc iopinfo ippinfo \
	slotctrl

.include <bsd.subdir.mk>
