#	$NecBSD: Makefile,v 1.10 1999/08/05 08:53:01 kmatsuda Exp $
#	$NetBSD$

# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.

PROG=	screenmode
BINDIR?=	/usr/local/bin
MKMAN=	no
LDFLAGS=	-g -static
LDADD=	-li386

.include <bsd.prog.mk>
