#	$NecBSD: Makefile,v 1.20 1999/08/05 08:52:54 kmatsuda Exp $
#	$NetBSD$

# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.

BINDIR?=	/usr/local/bin

PROG=	clock
MKMAN=	no
SRCS=	clock.c apmprint.c

.PATH: ../../../../util/usr.sbin/apmctrl

.include <bsd.prog.mk>
