#	$NecBSD: Makefile,v 1.3 1999/08/05 08:53:24 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

PROG=	diskinfo
MKMAN=	no

.include <bsd.prog.mk>
