#	$NecBSD: Makefile,v 1.10 1999/08/05 08:53:19 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

LIB=	pcmcia
SRCS=	pcmcia.c
MKMAN=	no
MKLINT=	no
LIBDIR=	/usr/local/lib
NOPROFILE=	noprofile
NOPIC=	nopic
CPPFLAGS+=	-g -I${.CURDIR}/../../../..

.include <bsd.lib.mk>
