#	$NecBSD: Makefile,v 1.7 1998/03/14 07:01:25 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	idectrl
NOMAN=	noman
BINDIR?=	/sbin
LDSTATIC=	-static
CFLAGS+=	-I${.CURDIR}/../../sys/arch

.include <bsd.prog.mk>
