#	$NecBSD: Makefile,v 1.10.6.1 1999/08/28 06:33:18 honda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

SUBDIR= apmconfig diskgen diskinfo dospart ippctrl pcsd vm86biosd vpdconfig ttycon bootflags

.include <bsd.subdir.mk>
