#	$NecBSD: Makefile.inc,v 1.8 1998/03/14 07:10:51 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

#WARNS?=	1
BINDIR?=	/sbin
LDSTATIC=	-static
