#	$NecBSD: Makefile,v 1.7 1998/03/15 03:22:30 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
#

PROG=	apmctrl
SRCS=	apmctrl.c apmprint.c

NOMAN=	noman

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
