#	$NecBSD: Makefile,v 1.5 1999/08/05 08:53:50 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	iopinfo
MKMAN=	no
#CFLAGS=	-g
#LDFLAGS=	-g
LDADD+=	-lkvm

.include <bsd.prog.mk>
