#	$NecBSD: Makefile,v 1.6 1998/03/14 07:10:40 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

SUBDIR= libpcmcia

.include <bsd.subdir.mk>
