# $NecBSD: Makefile,v 1.3 1999/08/05 08:52:45 kmatsuda Exp $
# $NetBSD: Makefile,v 1.3 1998/10/26 21:03:21 hubertf Exp $

INCSDIR= /usr/include/i386

INCS=   pcvt_ioctl.h

.ifdef	ORIGINAL_CODE
SUBDIR+= Util
.endif	# !PC-98

.include <bsd.kinc.mk>
