#	$NecBSD: Makefile,v 1.6 1998/03/14 07:02:01 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	vmocs
NOMAN=	vmocs
#CFLAGS=	-g
#LDFLAGS=	-g
LDADD=	-lkvm
BINDIR?=	/usr/local/bin

.include <bsd.prog.mk>
