#	$NecBSD: Makefile,v 1.6 1999/08/05 08:53:22 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996 NetBSD/pc98 porting staff.
#  All rights reserved.
# 

PROG=	diskgen
MKMAN=	no
CFLAGS+= -g
LDADD+=	-lcurses -ltermcap -g

.include <bsd.prog.mk>
