#	$NecBSD: Makefile,v 1.12 1998/03/14 07:01:52 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	wavplay
NOMAN=	noman
#CFLAGS=	-g
#LDFLAGS=	-g
BINDIR?=	/usr/local/bin

.include <bsd.prog.mk>
