#	$NecBSD: Makefile,v 1.8 1999/08/05 08:53:49 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=   fdc
MKMAN=	no

# XXX: ${BINDIR} should be /usr/bin for overriding fdformat/i386
LINKS=	${BINDIR}/fdc /usr/bin/fdformat

.include <bsd.prog.mk>
