#	$NecBSD: Makefile,v 1.16.2.1 1999/09/02 10:57:32 honda Exp $
#	$NetBSD$

# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1994, 1995, 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.

PROG=	vsc
MKMAN=	no
BINDIR?=	/usr/local/bin
CFLAGS+=	-I../.. -I../../../../..
LDSTATIC=	-static

.include <bsd.prog.mk>
