#	$NecBSD: Makefile,v 1.8 1998/03/15 03:23:39 kmatsuda Exp $
#	$NetBSD$
#
# [NetBSD for NEC PC-98 series]
#  Copyright (c) 1996, 1997, 1998
#	NetBSD/pc98 porting staff. All rights reserved.
# 

PROG=	ippinfo
MAN=	ippinfo.8
CFLAGS+=	-I${.CURDIR}/../../../..

.include <bsd.prog.mk>
